### ISSUE TITLE
切换路由地址的时候报了错

### ISSUE THREAD

**Issue by hrbzcj** [yoxjs/yox-router#1]
比如从/abc到/def，yox.js报错了
错误信息：Cannot read property 'off' of undefined
报错代码：
--------------------yox.js----------------------
/**
     * 销毁
     */

  }, {
    key: 'destroy',
    value: function destroy() {

      var instance = this;

      instance.$watchEmitter.off(); //【这里报错了】

      each$1(instance, function (value, key) {
        delete instance[key];
      });
    }
------------------------------------------------
另外能不能实现vue那样的嵌套路由？
我用vue是这样布局的：
/abc
头部1
路由占位符
尾部1

/abc的子路由/def
内容1（会替换/abc的路由占位符）

/abc的子路由/ghi
内容2（会替换/abc的路由占位符）

/login
内容3（/login页面没有头部和尾部）

/opq
头部2
路由占位符
尾部2

/opq的子路由/rst
内容4（会替换/opq的路由占位符）

**Comment by hrbzcj** [comment]
好像得改成：
instance.emitter.off();

**Comment by musicode** [comment]
居然有人用我的路由，感动，稍等，我看看问题

**Comment by musicode** [comment]
你说的对，这个问题是我周末重构改错了....

**Comment by musicode** [comment]
更新了版本，多谢使用！

**Comment by musicode** [comment]
更新了版本，多谢使用！

**Comment by musicode** [comment]
路由使用问题你新开一个 issue 专门讨论如何？
