### ISSUE TITLE
这个库支有像yox一样支持IE8的legacy目录吗 现在在IE8下无法正常运行

### ISSUE THREAD

**Issue by sunbinbin007** [yoxjs/yox-router#4]

**Comment by musicode** [comment]
这个库没有不兼容 IE8 的代码，只要用了 yox legacy 版本，应该是可以运行路由的，你说的不能运行能具体些吗

**Comment by sunbinbin007** [comment]
![IMG_6892](https://user-images.githubusercontent.com/13409926/68007176-ba83f100-fcb5-11e9-9421-6bb5404289cb.JPG)
![IMG_6893](https://user-images.githubusercontent.com/13409926/68007185-bf48a500-fcb5-11e9-859e-9047ac95a02f.JPG)

**Comment by musicode** [comment]
你试试 example/start.html 呢，yox 换成 legeacy 版本

**Comment by musicode** [comment]
调用了 `new YoxRouter.Router({...})` 之后，`this.mode` 肯定是存在的，不可能为空才对，除非你没调构造函数？

**Comment by sunbinbin007** [comment]
还是不行 ie9是可以的 功能正常

**Comment by musicode** [comment]
我试试，有结果再告诉你

**Comment by sunbinbin007** [comment]
好的 感谢

**Comment by musicode** [comment]
1.0.0-alpha.47 修复了

**Comment by sunbinbin007** [comment]
已验证 IE8下正常👍🏻

**Comment by musicode** [comment]
有问题或建议再反馈咯
