### ISSUE TITLE
ie8不支持router？

### ISSUE THREAD

**Issue by lilihaoo** [yoxjs/yox-router#5]
![image](https://user-images.githubusercontent.com/46394935/82316349-3d288f80-99ff-11ea-9d0c-6fde3067569b.png)
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8" />
        <title>yox-demo</title>
        <meta
            name="viewport"
            content="width=device-width, initial-scale=1.0, minimum-scale=1.0, maximum-scale=1.0, user-scalable=0"
        />
        <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1" />
        <meta name="format-detection" content="telephone=no" />
        <meta name="format-detection" content="email=no" />

        

        

        
    </head>
    <body>
        <div id="app"></div>
        <script src="./yox.js"></script>
        <script src="./yox-router.js"></script>
        <script>
            Yox.use(YoxRouter)

            var router = new YoxRouter.Router({
                el: Yox.dom.find('#app'),
                routes: [
                    {
                        path: '',
                        name: 'header_tpl',
                        component: {
                            template: ['<div class="header">', '<h1>header</h1>', '</div>'].join(
                                ''
                            ),
                        },
                    },
                ],
                route404: {
                    path: '404',
                    name: '404',
                    component: {
                        template: '<div>not found</div>',
                    },
                },
            })

            router.start()
        </script>
    </body>
</html>

**Comment by musicode** [comment]
应该是支持的，晚点我看下再回复你

**Comment by musicode** [comment]
![image](https://user-images.githubusercontent.com/2732303/82341191-ac63ab00-9a22-11ea-9097-88f3023f1359.png)
我测试没问题，应该是你使用有问题

**Comment by lilihaoo** [comment]
可以问下你是在哪个系统版本下验证的，ie8的浏览器还是模拟的版本；我这边用了这个案例，ie11模拟ie8还是不行；xp上的ie8也不行

**Comment by musicode** [comment]
win7 下的原生 ie8，你试下 example/start.html

**Comment by lilihaoo** [comment]
找到问题了
![image](https://user-images.githubusercontent.com/46394935/82534913-9bc54900-9b78-11ea-9c4e-81887d6e1b77.png)
这边代码编译器默认开启的保存自动格式化，使用的prettier插件，对象或数组的结尾默认加了个逗号，这个逗号导致了yox-router以为还有的route而报的错，routes数组最后一个对象的逗号删掉ie8就可以访问了；一个逗号折磨我两天

**Comment by musicode** [comment]
哈哈，是的，这个问题我也碰到过

**Comment by lilihaoo** [comment]
![image](https://user-images.githubusercontent.com/46394935/82535879-2490b480-9b7a-11ea-8f3e-a81c25efecd4.png)

**Comment by musicode** [comment]
低版本ie是这样的行为，没毛病
